# -*- coding: utf-8 -*-
"""yolov8 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WmChSOkESbumekl7Ia2bnIY7hHC1sLWl
"""

import os
HOME = os.getcwd()
print(HOME)

! pip install ultralytics==8.0.196

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

# Commented out IPython magic to ensure Python compatibility.
! mkdir {HOME}/datasets
# %cd {HOME}/datasets

! pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="3OEqKlaUTLNgrFZGJiv6")
project = rf.workspace("kashish").project("3riders")
version = project.version(2)
dataset = version.download("yolov8")

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

! yolo task=detect mode=train model=yolov8s.pt data="c:/Users/Haard Shah/Downloads/data.yaml" epochs=100 imgsz=800 plots=True

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/confusion_matrix.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/results.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/val_batch0_pred.jpg', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=val model={HOME}/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=predict model={HOME}/runs/detect/train/weights/best.pt conf=0.25 source={dataset.location}/test/images save=True

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'{HOME}/runs/detect/predict/*.jpg')[:10]:
      display(Image(filename=image_path, width=600))
      print("\n")

+